version: "3.8"
services:
  backend:
    image: "715841341879.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-fargate/backend"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: "715841341879.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-fargate/frontend"
    ports:
      - "80:80"
