name: "Deploy to Amazon ECS"

on:
  workflow_call:
    inputs:
      aws-region:
        description: "AWS region (for example, ap-northeast-1)"
        required: true
        type: string
      cluster:
        description: "ECS cluster name"
        required: true
        type: string
      service:
        description: "ECS service name"
        required: true
        type: string
      task-definition-file:
        description: "Path to ECS Task Definition JSON (e.g., 'ecs/task-def.json')"
        required: true
        type: string
      container-name:
        description: "Name of the container in the Task Definition"
        required: true
        type: string
      image-repo-name:
        description: "ECR image Repo name"
        required: true
        type: string
      ecr-repo-url:
        description: "ECR image url"
        required: true
        type: string
      context:
        description: "Context"
        required: false
        default: backend
        type: string
      env:
        description: "environment"
        required: true
        default: staging
        type: string
      port:
        description: "PORT to pass as build-arg"
        required: false
        default: "80"
        type: string
      deploy:
        description: "true: deploy, false: don't deploy"
        required: false
        default: false
        type: boolean

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: ${{ inputs.cluster }}
      SERVICE_NAME: ${{ inputs.service }}
      TASK_DEFINITION_NAME: ${{ inputs.task-definition-file }}
      IMAGE_REPO_NAME: ${{ inputs.image-repo-name }}
      ECR_REPO_URL: ${{ inputs.ecr-repo-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REPO_URL }}
      - name: Build
        uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/Dockerfile
          push: true
          tags: ${{ env.ECR_REPO_URL }}/${{ env.IMAGE_REPO_NAME }}:latest
          build-args: |
            PORT=${{ inputs.port }}
            ENV=${{ inputs.env }}
      - name: Render Amazon ECS task definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ inputs.task-definition-file }}
          container-name: ${{ inputs.container-name }}
          image: ${{ env.ECR_REPO_URL }}/${{ env.IMAGE_REPO_NAME }}:latest

      - name: Deploy to Amazon ECS service
        if: ${{ inputs.deploy == true }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ env.CLUSTER_NAME }}
          service: ${{ env.SERVICE_NAME }}
          task-definition: ${{ inputs.task-definition-file }}
          wait-for-service-stability: true
